### PR TITLE
i add app.js file in the project.

### PR DESCRIPTION
**Pull request by mehranali12**
you can see my simple changes..

### CODE REVIEW

**Comment by mehranali12** [comment]
this is simple app.js file.

**Comment by SayeedAfridi** [comment]
No app.js file required! You can write js in a ts file..

**Review by mehranali12 — COMMENTED** [review]
is not sir

**Comment by mehranali12** [comment]
how it not pull.......

**Comment by SayeedAfridi** [comment]
It is an unnecessary pull request.. We already have App.tsx file.. Check
our code.. If you fetch any problem tell me..

**Comment by mehranali12** [comment]
sir do see my pull request

**Comment by SayeedAfridi** [comment]
yeah.. I see it.. Only one changes and it adds app.js file..

**Pull request closed without merging**
