### PR TITLE
Hiren All Changes

### PR DESCRIPTION
**Pull request by Amarpsp10**

### CODE REVIEW

**Comment by Amarpsp10** [comment]
In `Android11`  page `AssignmentSummary` Design Issue and Safe Area Provider not used!

**Comment by Amarpsp10** [comment]
In Android Page `Create Assignment` Is not Scrollable (not working) and no Safe Area

**Comment by Amarpsp10** [comment]
All the New Pages are not scrollable in `Android` @dudhathiren please check

**Comment by fuelupeducation** [comment]
Do not delete branch

**Pull request merged**
